#==========================================
#	Copyright 2024 
#		Yoda Ryunosuke
#		(Takoyaki@neonz.net)
#==========================================
#実行ファイル名
TARGET=neodog 
#生成したい静的ライブラリ名
NAME =neodog
#コンパイル対象としたいプログラム
SRCS =neodog.c
#コンパイラの指定
CC=gcc

#あとで追加する